### ISSUE TITLE
.c for two integers

### ISSUE THREAD

**Issue by willsherwood** [isaacg1/pyth#105]
.c for two integers could be the combinations formula, nCr: n!/r!(n-r)!

**Comment by orlp** [comment]
I love it.

Where do we put nPr?

**Comment by orlp** [comment]
Hmm, I was thinking that maybe we should have the factorial somewhere as well. We can't put it in `.p` however, because `.p3` -> `[[0, 1, 2], [0, 2, 1], [1, 0, 2], [1, 2, 0], [2, 0, 1], [2, 1, 0]]`.

**Comment by jakobkogler** [comment]
Yeah, we definitely need a shorter factorial. `*Fr1hQ` is just too long. I would suggest either `.*` or `.x`. 

The first one `.*` (unpack) has absolutely no use at all. It can always be replaced by `F` or `.u`.  At least until were upgrading to Python 3.5, where something like `[1 2.*U3 4)` might be possible. And I'm not sure, if this would save any bytes at all, since you could also do `s[Y1 2U3 4)`. 

The second one is also not really useful. `.x` with a sequence can always be replaced by `*F`. And setting the random seed with an int, could be easily relocated to `O_`. 

But back to the topic. I also find, that calculating nCr or nPr could be useful. There are some challenges, which require a certain speed, so that a brute force approach wouldn't work. Using `.c<int><int>` and `.p<int><int>` wouldn't hurt, since we could easily simulate their current behavior with `.cU<int><int>` and `.pU<int><int>`. Only one byte. 

Some other thought, we also could combine nCr and nPr into only one function. Which calculates the nCr, if the first arg is bigger than the second, and the nPr otherwise.

**Comment by orlp** [comment]
`.x` came before `*F` and is now indeed obsolete. The seeding can indeed be moved, but not to `O_` - we need to find a different place for it.

I'm not too excited by the idea of having nCr and nPr under the same function - I think we have perfect candidates as-is with `.c` and `.P`.

**Comment by isaacg1** [comment]
I agree with removing `.x` and `.*`, and with adding nCr and nPr. I would prefer putting them under `.c` and `.P` than making new functions for them.

**Comment by orlp** [comment]
Made a separate issue for the useless functions: https://github.com/isaacg1/pyth/issues/108 .

**Comment by isaacg1** [comment]
Merged.
