### ISSUE TITLE
What is arity X, S, and |?

### ISSUE THREAD

**Issue by winny-** [isaacg1/pyth#131]
I'm not sure if there is a better place to ask general questions about Pyth, so I'm creating an issue.

I noticed in the `doc.txt` there isn't any discussion about what arities X, S, and | mean. Is there documentation elsewhere that discusses these arities?

**Comment by isaacg1** [comment]
There isn't any documentation for those, thanks for pointing it out. I'll add the documentation to `doc.txt`.
`X` means exceptional, it means that the character doesn't fit in the arity system. `S` means statement, because statements can have bodies of any length. `I` means infinite, or in other words unbounded. `|` isn't used. Please note that that part of the documentation may be somewhat inconsistent, as it is not well maintained.
